# Generated by Django 4.2.3 on 2023-08-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
