# Generated by Django 4.2.3 on 2023-08-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_category_addbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='desc',
        ),
    ]
