# Generated by Django 4.2.3 on 2023-08-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0009_bookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='approval_status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Approved', 'Approved')], default='Pending Approval', max_length=20),
        ),
    ]
