# Generated by Django 4.2.3 on 2023-08-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0012_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
