# Generated by Django 4.2.3 on 2023-08-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0014_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRequest',
        ),
    ]
