# Generated by Django 4.2.3 on 2023-08-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0016_bookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='issued',
            field=models.BooleanField(default=False),
        ),
    ]
