# Generated by Django 4.2.3 on 2023-08-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0021_bookrequest_due_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
