# Generated by Django 4.2.3 on 2023-08-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0023_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='image',
            new_name='img',
        ),
    ]
