# Generated by Django 4.2.3 on 2023-08-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0024_rename_image_signup_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
