# Generated by Django 4.2.3 on 2023-09-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0028_signuprequestnotification_signuprequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupRequest',
        ),
    ]
