# Generated by Django 4.2.3 on 2023-09-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0030_signuprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signuprequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signuprequest',
            name='name',
        ),
    ]
