# Generated by Django 4.2.3 on 2023-09-03 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryapp', '0031_remove_signuprequest_email_remove_signuprequest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuprequestnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
