# Generated by Django 4.2.3 on 2023-09-04 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0032_alter_signuprequestnotification_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
