# Generated by Django 4.2.3 on 2023-09-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0035_usernotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRequest',
        ),
    ]
