# Generated by Django 4.2.3 on 2023-09-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0039_alter_bookrequest_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRequest',
        ),
    ]
