# Generated by Django 4.2.3 on 2023-09-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0043_bookrequest_additional_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemreport',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
