# Generated by Django 4.2.3 on 2023-09-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0046_overduebooknotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
