# Generated by Django 4.2.3 on 2023-09-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0048_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='overdue',
            field=models.CharField(default='Not Overdue', max_length=20),
        ),
    ]
