# Generated by Django 4.2.3 on 2023-09-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0049_bookrequest_overdue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='issue_type',
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='request_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
