# Generated by Django 4.2.3 on 2023-09-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0052_bookrequest_fine_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='overdue',
            field=models.CharField(max_length=20),
        ),
    ]
