# Generated by Django 4.2.7 on 2023-12-09 22:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0053_alter_bookrequest_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='overdue_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Overdue amount in currency', max_digits=10),
        ),
    ]
