# Generated by Django 4.2.3 on 2023-12-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0054_bookrequest_overdue_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='qty',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
