# Generated by Django 4.2.3 on 2023-12-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0056_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
