# Generated by Django 4.2.3 on 2023-12-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0057_bookrequest_returned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
